# Generated by Django 5.0.4 on 2024-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_category',
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.product'),
        ),
    ]
