# Generated by Django 5.0.4 on 2024-05-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productcategories_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_categories', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='id_flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_product', to='shop.flower'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_product', to='shop.product'),
        ),
        migrations.DeleteModel(
            name='ProductCategories',
        ),
    ]
