# Generated by Django 5.0.4 on 2024-05-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category_alter_composition_id_flower_and_more'),
    ]

    operations = [
    ]
