# Generated by Django 5.0.4 on 2024-05-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240505_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-19 16:57:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='id_flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='shop.flower'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Доставлено', 'Доставлено')], default='В ожидании', max_length=200),
        ),
        migrations.AlterField(
            model_name='productlabels',
            name='id_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_choice', to='shop.label'),
        ),
        migrations.AlterField(
            model_name='productlabels',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_labels', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productlabels',
            unique_together={('id_label', 'id_product')},
        ),
    ]
