# Generated by Django 5.0.4 on 2024-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_created_order_updated_review_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(related_name='product_labels', to='shop.label'),
        ),
        migrations.DeleteModel(
            name='ProductLabels',
        ),
    ]
