# Generated by Django 5.0.4 on 2024-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_application_order_discount_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
